myfirstapp/urls.py
from django.urls import path
from . import views

app_name = "myfirstapp"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:estudiante_id>/carreras/", views.carreras, name="carreras"),
    path("<int:estudiante_id>/detalles/", views.detalles, name="detalles"),
    path("<int:estudiante_id>/<int:tipo>/<str:nombre>/agrega_carrera/", views.agrega_carrera, name="agrega_carrera"),
    path("<str:nombre>/<str:apellidos>/<int:edad>/<str:foraneo>/<str:promedio>/agrega_estudiante/", views.agrega_estudiante, name="agrega_estudiante"),    
    path("<int:estudiante_id>/<str:promedio>/edita_estudiante/", views.edita_estudiante, name="edita_estudiante"),
    path("<int:estudiante_id>/borra_estudiante/", views.borra_estudiante, name="borra_estudiante"),
    path("agrega_estudiante_forma", views.agrega_estudiante_forma, name="agrega_estudiante_forma"),    
    path("asincrona/", views.asincrona, name="asincrona"),
]

mywebsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("myfirstapp/", include("myfirstapp.urls")),
    path("admin/", admin.site.urls),

]

myfirstapp/models.py
from django.db import models

class Estudiante(models.Model):
    nombre = models.CharField(max_length=200)
    apellidos = models.CharField(max_length=200)
    edad = models.IntegerField(default=0)
    promedio = models.FloatField(default=9.99)
    foraneo = models.BooleanField(default=False)

    def __str__(self):
        return self.nombre + " " + self.apellidos
    
    def aspira_a_beca(self):
        return self.promedio >= 9

class Carrera(models.Model):
    LICENCIATURA = 1
    INGENIERIA = 2
    OPCIONES_TIPO = (
        (LICENCIATURA, "Licenciatura"),
        (INGENIERIA, "Ingenieria"),
    )
    estudiante = models.ForeignKey(Estudiante, on_delete=models.CASCADE)
    tipo = models.IntegerField(choices=OPCIONES_TIPO, null=True, blank=True)
    nombre = models.CharField(max_length=200)

    def __str__(self):
        return str(self.tipo) + " " + self.nombre 
    def get_tipo(self):
        return Carrera.OPCIONES_TIPO[self.tipo-1][1]

myfirstapp/views.py
from django.shortcuts import render, get_object_or_404
from django.template import loader
from django.http import HttpResponse, Http404
from .models import Estudiante

import requests;

def index(request):
    estudiantes = Estudiante.objects.order_by("nombre")
    context = {
        "estudiantes": estudiantes,
    }
    return render(request, "myfirstapp/index.html", context)

async def asincrona(request):
    url = "http://localhost:90/clasificaapi"
    respuesta = requests.post(url, json={"frecuencia":200})
    print("-------------------",respuesta)
    print(respuesta.json()) 
    return HttpResponse("Respuesta asincrona %s." % respuesta.json())

def detalles(request, estudiante_id):
    estudiante = get_object_or_404(Estudiante, pk=estudiante_id)
    return render(request, "myfirstapp/detalles.html", 
		{"estudiante": estudiante})




def carreras(request, estudiante_id):
    return HttpResponse("Carreras del estudiante %s." % estudiante_id)

def agrega_carrera(request, estudiante_id, tipo, nombre):
    estudiante = Estudiante.objects.get(pk=estudiante_id)
    estudiante.carrera_set.create(tipo = int(tipo), nombre=nombre)
    return HttpResponse("Carrera agregada al estudiante %s" % estudiante_id)

def agrega_estudiante(request, nombre, apellidos, edad, foraneo, promedio):
    foraneo = foraneo.lower() == "true"
    estudiante = Estudiante(	nombre=nombre, 
				apellidos=apellidos, 
				edad=int(edad), 
				foraneo=foraneo, 
				promedio=float(promedio))
    estudiante.save()
    return HttpResponse("Estudiante %s agregado exitósamente" % estudiante.id)

def borra_estudiante(request, estudiante_id):
    estudiante = Estudiante.objects.get(pk=estudiante_id)
    estudiante.delete()
    return HttpResponse("Estudiante %s borrado exitósamente" % estudiante_id)


def edita_estudiante(request, estudiante_id, promedio):
    estudiante = Estudiante.objects.get(pk=estudiante_id)
    estudiante.promedio = float(promedio)
    estudiante.save()    
    return HttpResponse("El promedio del estudiante %s se ha actualizado exitósamente" % estudiante.id)

def agrega_estudiante_forma(request):
    nombre = request.POST.get("nombre")
    apellidos = request.POST.get("apellidos")
    edad = int(request.POST.get("edad"))
    if "foraneo" in request.POST:
        foraneo = True
    else:
        foraneo = False
    promedio = float(request.POST.get("promedio"))
    estudiante = Estudiante(	nombre=nombre, 
				apellidos=apellidos, 
				edad=int(edad), 
				foraneo=foraneo, 
				promedio=float(promedio))
    estudiante.save()
    return HttpResponse("Estudiante %s agregado exitósamente desde la forma" % estudiante.id)


myfirstapp/templates/myfirstapp/detalles.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Detalles</title>
  </head>
  <body>
        <p> Información del Estudiante </p>
        {% if estudiante %}
            <p>{{ estudiante.id }} </p>
            <p>{{ estudiante.nombre }} 
            <p>{{ estudiante.apellidos }} </p>
            <p>{{ estudiante.promedio }} </p>
            {% if estudiante.foraneo %}
                <p>Foráneo</p>
            {% else %}
                <p>Local </p>
            {% endif %}
            <ul>
                {% for carrera in estudiante.carrera_set.all %}
                    <li> {{ carrera.get_tipo }} {{ carrera.nombre }} </li>    
                {% endfor %}
                </ul>
        {% endif %}       
  </body>
</html>

myfirstapp/templates/myfirstapp/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Index page</title>
    {% load static %}
    <link	rel="stylesheet" type="text/css" href="{% static 'myfirstapp/style.css' %}">
    
    {% load static %}
    <script src="{% static 'myfirstapp/javascript.js' %}"></script>

  </head>
  <body>

    <p>Listado de estudiantes</p>
    {% if estudiantes %}
    <ul>
    {% for estudiante in estudiantes %}

    <li><a href="{% url 'myfirstapp:detalles' estudiante.id %}">
        {{estudiante.nombre}}
        {{estudiante.apellidos}} 
    </a></li>  
    

    {% endfor %}
    </ul>
    {% else %}
        <p>No hay estudiantes registrados.</p>
    {% endif %}

    <form action="agrega_estudiante_forma" method="POST">
        {%csrf_token%}
        <label> Nombre: <input type="text" name = "nombre"> </label> <br>
        <label> Apellidos: <input type="text" name = "apellidos"> </label><br>
        <label> Edad: <input type="text" name = "edad"> </label><br>
        <label> Promedio: <input type="text" name = "promedio"> </label><br>
        <label> <input type="checkbox" value="True" name="foraneo"> Foráneo </label><br>
        <input type="submit" value="Agregar">
    </form>
    <input type="button" value="Función asíncrona" onclick="asincrona();">
    
  </body>
</html>